apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-app
  annotations:
    keel.sh/policy: "automated"
    keel.sh/trigger: "webhook"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spark-app
  template:
    metadata:
      labels:
        app: spark-app
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: spark-app
        image: abhijitdhamne/spark-pi:2cf5bac 
        imagePullPolicy: "Always"
        ports:
        - containerPort: 4040
