apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-spark-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apache-spark-app
  template:
    metadata:
      labels:
        app: apache-spark-app
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: apache-spark-app
        image: abhijitdhamne/spark-app:0e2a619 
        imagePullPolicy: "Always"
        ports:
        - containerPort: 4040
